import "./globals.css";
import { Inter } from "next/font/google";
import "../styles/global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="R2qvZ3hNbmVD5gS-3j-Y7nOZRajJwevK_LMdatrQAKA"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
