import "./globals.css";
import { Inter } from "next/font/google";
import "../styles/global.css";
// import ProgressBar from "@badrap/bar-of-progress";
// import Router from "next/navigation";

// const progress = new ProgressBar({
//   size: 4,
//   color: "#FE595E",
//   className: "z-50",
//   delay: 100,
// });

// Router.events.on("routeChangeStart", progress.start);
// Router.events.on("routeChangeComplete", progress.finish);
// Router.events.on("routeChangeError", progress.finish);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
